export const PAYMENT_START="PAYMENT_START";
export const PAYMENT_FAIL="PAYMENT_FAIL";
export const PAYMENT_GET="PAYMENT_GET"
export const PAYMENTS_GET="PAYMENTS_GET"
export const PAYMENT_CREATE="PAYMENT_CREATE"
export const PAYMENT_UPDATE="PAYMENT_UPDATE"
export const PAYMENT_DELETE="PAYMENT_DELETE"