export const CATAGORY_START ="CATAGORY_START"
export const CATAGORY_SUCCESS="CATAGORY_SUCCESS"
export const CATAGORY_FAIL="CATAGORY_FAIL"

export const CATAGORY_GET="CATAGORY_GET"
export const CATAGORY_CREATE="CATAGORY_CREATE"
